describe('EPAs Carbon Footprint Calculator Home Energy', () => {

    beforeEach(() =>{
        cy.visit('https://www3.epa.gov/carbon-footprint-calculator/') 
    })

    // TESTES COM VARIACAO DE FONTE DE AQUECIMENTO E SEM CARRO E DESCARTE

    it.only('Teste com 1 pessoa com princicpal fonte de aquecimento "Natural Gas" usando gastos padroes, sem carro e sem descarte de residuos', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345') 
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })

    it('Teste com 1 pessoa com princicpal fonte de aquecimento "Electricity" usando gastos padroes, sem carro e sem descarte de residuos', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Electricity')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })

    it('Teste com 1 pessoa com princicpal fonte de aquecimento "Fuel Oil" usando gastos padroes, sem carro e sem descarte de residuos', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Fuel Oil')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })

    it('Teste com 1 pessoa com princicpal fonte de aquecimento "Propane" usando gastos padroes, sem carro e sem descarte de residuos', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Propane')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })

    // TESTES COM VARIACAO DE GASTOS E SEM CARRO E DESCARTE

    it('Teste com 1 pessoa com princicpal fonte de aquecimento "Natural Gas" com valores de gastos em 0 dolar, sem carro e sem descarte de residuos', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('0')
        cy.get('#electricityTextInput').type('0')
        cy.get('#electricityGreenTextInput').type('0')
        cy.get('#fuelTextInput').type('0')
        cy.get('#propaneTextInput').type('0')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })

    it('Teste com 1 pessoa com princicpal fonte de aquecimento "Natural Gas" com valores de gastos em 1000 dolar, sem carro e sem descarte de residuos', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('1000')
        cy.get('#electricityTextInput').type('1000')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('1000')
        cy.get('#propaneTextInput').type('1000')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })

    // TESTES COM VARIACAO DE REDUCAO DE EMISSAO E SEM CARRO E DESCARTE

    it('Teste com 1 pessoa com princicpal fonte de aquecimento "Natural Gas" usando gastos padroes, preenchendo todos os campos de reducao e com valor 0 com opcao "Will Do" sem carro e sem descarte de residuos', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')

        cy.get('#energyAC').type('0')
        cy.get('#energyHeat').type('0')
        cy.get('#lightsToReplace').type('0')
        cy.get('#pwrMgmtSelect').select('Will Do')
        cy.get('#increaseGreenInput').type('0')
        cy.get('#coldWaterSelect').select('Will Do')
        cy.get('#loadsPerWeek').type('2')
        cy.get('#AirDrySelect').select('Will Do')
        cy.get('#percentageAirDrySelect').select('10% of my Laundry')
        cy.get('#fridgeSelect').select('Will Do')
        cy.get('#furnaceSelect').select('Will Do')
        cy.get('#windowSelect').select('Will Do')

        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })

    it('Teste com 1 pessoa com princicpal fonte de aquecimento "Natural Gas" usando gastos padroes, preenchendo todos os campos de reducao e com valor 0 com opcao "Will Not Do" sem carro e sem descarte de residuos', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')

        cy.get('#energyAC').type('0')
        cy.get('#energyHeat').type('0')
        cy.get('#lightsToReplace').type('0')
        cy.get('#pwrMgmtSelect').select('Will Not Do')
        cy.get('#increaseGreenInput').type('0')
        cy.get('#coldWaterSelect').select('Will Not Do')
        cy.get('#loadsPerWeek').type('2')
        cy.get('#AirDrySelect').select('Will Not Do')
        cy.get('#percentageAirDrySelect').select('10% of my Laundry')
        cy.get('#fridgeSelect').select('Will Not Do')
        cy.get('#furnaceSelect').select('Will Not Do')
        cy.get('#windowSelect').select('Will Not Do')

        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })

    it('Teste com 1 pessoa com princicpal fonte de aquecimento "Natural Gas" usando gastos padroes, preenchendo todos os campos de reducao e com valor 0 com opcao "Already Done", sem carro e sem descarte de residuos', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')

        cy.get('#energyAC').type('0')
        cy.get('#energyHeat').type('0')
        cy.get('#lightsToReplace').type('0')
        cy.get('#pwrMgmtSelect').select('Already Done')
        cy.get('#increaseGreenInput').type('0')
        cy.get('#coldWaterSelect').select('Already Done')
        cy.get('#loadsPerWeek').type('2')
        cy.get('#AirDrySelect').select('Already Done')
        cy.get('#percentageAirDrySelect').select('10% of my Laundry')
        cy.get('#fridgeSelect').select('Already Done')
        cy.get('#furnaceSelect').select('Already Done')
        cy.get('#windowSelect').select('Already Done')

        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })

    it('Teste com 1 pessoa com princicpal fonte de aquecimento "Natural Gas" usando gastos padroes, preenchendo todos os campos de reducao e com valor padrao com opcao "Will Do" sem carro e sem descarte de residuos', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')

        cy.get('#energyAC').type('70')
        cy.get('#energyHeat').type('70')
        cy.get('#lightsToReplace').type('5')
        cy.get('#pwrMgmtSelect').select('Will Do')
        cy.get('#increaseGreenInput').type('50')
        cy.get('#coldWaterSelect').select('Will Do')
        cy.get('#loadsPerWeek').type('2')
        cy.get('#AirDrySelect').select('Will Do')
        cy.get('#percentageAirDrySelect').select('All my Laundry')
        cy.get('#fridgeSelect').select('Will Do')
        cy.get('#furnaceSelect').select('Will Do')
        cy.get('#windowSelect').select('Will Do')

        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })

    // TESTES NEGATIVOS

    it('Caso de teste de uma casa com 1 pessoa no zipcode 12345 que não seja selecionado a principal fonte de aquecimento e siga preenchimento de campos aleatórios e gere um erro', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#errorMessageBox').should('be.visible')
        cy.get('.errorMessageBox > .ui-dialog-titlebar > .ui-dialog-titlebar-close > .ui-icon').click()
    })

    // it('Caso de teste de uma casa com 1 pessoa no zipcode 12345 que não seja selecionado a principal fonte de aquecimento e siga preenchimento para outra seção', () => {
    //     cy.get('#ppl-in-household-input').type('1')
    //     cy.get('#zip-code-input').type('12345')
    //     cy.get('#get-started').click()
    //     cy.wait(3000)
    //     cy.get('.sectionName').contains('Home Energy').should('be.visible')
    //     cy.scrollTo(500, 0)
    // })

    it('Caso de teste de uma casa com 1 pessoa no zipcode 12345 com principal fonte de aquecimento o “Natural Gas” e que siga preenchimento de outros campos e não preencha o valor da fonte de aquecimento selecionada', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#energyHeat').type('70')
        cy.get('#errorMessageBox').should('be.visible')
        cy.get('#error-monthly-utility').should('have.text', 'You must have an entry for Monthly Natural Gas bill.')
    })

    it('Caso de teste de uma casa com 1 pessoa no zipcode 12345 com principal fonte de aquecimento o “Electricity” e que siga preenchimento de outros campos e não preencha o valor da fonte de aquecimento selecionada', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Electricity')
        cy.get('#energyHeat').type('70')
        cy.get('#errorMessageBox').should('be.visible')
        cy.get('#error-monthly-utility').should('have.text', 'You must have an entry for Monthly Electricity bill.')
    })

    it('Caso de teste de uma casa com 1 pessoa no zipcode 12345 com principal fonte de aquecimento o “Fuel Oil” e que siga preenchimento de outros campos e não preencha o valor da fonte de aquecimento selecionada', () => {   
        //cy.residents_zipcode('1', '12345')
        cy.get('#ppl-in-household-input').type(people)
        cy.get('#zip-code-input').type(zipcode)
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Fuel Oil')
        cy.get('#energyHeat').type('70')
        cy.get('#errorMessageBox').should('be.visible')
        cy.get('#error-monthly-utility').should('have.text', 'You must have an entry for Monthly Fuel Oil bill.')
    })

    it('Caso de teste de uma casa com 1 pessoa no zipcode 12345 com principal fonte de aquecimento o “Propane” e que siga preenchimento de outros campos e não preencha o valor da fonte de aquecimento selecionada', () => {   
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Propane')
        cy.get('#energyHeat').type('70')
        cy.get('#errorMessageBox').should('be.visible')
        cy.get('#error-monthly-utility').should('have.text', 'You must have an entry for Monthly Propane bill.')
        })



})