describe('EPAs Carbon Footprint Calculator Report', () => {

    beforeEach(() =>{
        cy.visit('https://www3.epa.gov/carbon-footprint-calculator/')
    })

    it('Teste de uma casa com 1 pessoa no zipcode 12345 com gastos padrões que resultado da soma dos gastos seja menor que a media dos Estados Unidos;', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')

        cy.get('#good-work-msg').should('be.visible')

    })

    it('Teste de uma casa com 1 pessoa no zipcode 12345 com gastos padrões que resultado da soma dos gastos seja maior que a media dos Estados Unidos;', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('1000')
        cy.get('#electricityTextInput').type('1000')
        cy.get('#electricityGreenTextInput').type('0')
        cy.get('#fuelTextInput').type('1000')
        cy.get('#propaneTextInput').type('1000')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    
        cy.get('#good-work-msg').should('not.be.visible')
    
    })

    it('Teste de uma casa com 1 pessoa no zipcode 12345 com gastos padrões que seja exibido apenas “Home Energy” no relatorio final', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')

        cy.get('#transKey').click()
        cy.get('#wasteKey').click()

        cy.get('#current-total > .rowChart > .rowItems > .homeEnergyCharItem').should('be.visible')
        cy.get('#current-total > .rowChart > .rowItems > .transportationCharItem').should('not.be.visible')
        cy.get('#current-total > .rowChart > .rowItems > .wasteCharItem').should('not.be.visible')

        cy.get('#new-total > .rowChart > .rowItems > .homeEnergyCharItem').should('be.visible')
        cy.get('#new-total > .rowChart > .rowItems > .transportationCharItem').should('not.be.visible')
        cy.get('#new-total > .rowChart > .rowItems > .wasteCharItem').should('not.be.visible')

        cy.get('#us-avg > .rowChart > .rowItems > .homeEnergyCharItem').should('be.visible')
        cy.get('#us-avg > .rowChart > .rowItems > .transportationCharItem').should('not.be.visible')
        cy.get('#us-avg > .rowChart > .rowItems > .wasteCharItem').should('not.be.visible')
    })

    it('Teste de uma casa com 1 pessoa no zipcode 12345 com gastos padrões que seja exibido apenas “Transportation” no relatorio final', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')

        cy.get('#homeKey').click()
        cy.get('#wasteKey').click()

        cy.get('#current-total > .rowChart > .rowItems > .homeEnergyCharItem').should('not.be.visible')
        cy.get('#current-total > .rowChart > .rowItems > .transportationCharItem').should('be.visible')
        cy.get('#current-total > .rowChart > .rowItems > .wasteCharItem').should('not.be.visible')

        cy.get('#new-total > .rowChart > .rowItems > .homeEnergyCharItem').should('not.be.visible')
        cy.get('#new-total > .rowChart > .rowItems > .transportationCharItem').should('be.visible')
        cy.get('#new-total > .rowChart > .rowItems > .wasteCharItem').should('not.be.visible')

        cy.get('#us-avg > .rowChart > .rowItems > .homeEnergyCharItem').should('not.be.visible')
        cy.get('#us-avg > .rowChart > .rowItems > .transportationCharItem').should('be.visible')
        cy.get('#us-avg > .rowChart > .rowItems > .wasteCharItem').should('not.be.visible')
    })

    it('Teste de uma casa com 1 pessoa no zipcode 12345 com gastos padrões que seja exibido apenas “Transportation” no relatorio final', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')

        cy.get('#homeKey').click()
        cy.get('#transKey').click()

        cy.get('#current-total > .rowChart > .rowItems > .homeEnergyCharItem').should('not.be.visible')
        cy.get('#current-total > .rowChart > .rowItems > .transportationCharItem').should('not.be.visible')
        cy.get('#current-total > .rowChart > .rowItems > .wasteCharItem').should('be.visible')

        cy.get('#new-total > .rowChart > .rowItems > .homeEnergyCharItem').should('not.be.visible')
        cy.get('#new-total > .rowChart > .rowItems > .transportationCharItem').should('not.be.visible')
        cy.get('#new-total > .rowChart > .rowItems > .wasteCharItem').should('be.visible')

        cy.get('#us-avg > .rowChart > .rowItems > .homeEnergyCharItem').should('not.be.visible')
        cy.get('#us-avg > .rowChart > .rowItems > .transportationCharItem').should('not.be.visible')
        cy.get('#us-avg > .rowChart > .rowItems > .wasteCharItem').should('be.visible')
    })

    it('Teste de uma casa com 1 pessoa no zipcode 12345 com gastos padrões que seja exibido apenas “Transportation” no relatorio final', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')

        cy.get('#printicon').should('be.visible')
    })

    it('Teste de uma casa com 1 pessoa no zipcode 12345 com gastos padrões que seja exibido apenas “Transportation” no relatorio final', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')

        cy.get('#openSharePanel').should('be.visible')
    })

    it.only('Teste de uma casa com 1 pessoa no zipcode 12345 com gastos padrões que seja exibido apenas “Transportation” no relatorio final', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')

        cy.get('#small-actions > :nth-child(1) > h2').should('be.visible')
    })

})