describe('EPAs Carbon Footprint Calculator Waste Page', () => {

    beforeEach(() =>{
        cy.visit('https://www3.epa.gov/carbon-footprint-calculator/')
    })

    // TESTES COM VARIACAO DE DESCARTES

    it('Teste com 1 pessoa com princicpal fonte de aquecimento "Natural Gas" usando gastos padroes, sem carro e sem descarte de residuos', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()
        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })

    it('Teste com 1 pessoa com princicpal fonte de aquecimento "Natural Gas" usando gastos padroes, sem carro e reciclando apenas plástico', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()

        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#plasticCheckbox').click()

        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })

    it('Teste com 1 pessoa com princicpal fonte de aquecimento "Natural Gas" usando gastos padroes, sem carro e reciclando todas opções', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click()
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()

        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#plasticCheckbox').click()
        cy.get('#aluminumCheckbox').click()
        cy.get('#glassCheckbox').click()
        cy.get('#newspaperCheckbox').click()
        cy.get('#magazinesCheckbox').click()

        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })

    it('Teste com 1 pessoa com princicpal fonte de aquecimento "Natural Gas" usando gastos padroes, sem carro e sem descarte de residuos e iniciando a reciclagem apenas de vidro', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click() 
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()

        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#glassCheckboxR').click()
        
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })

    it('Teste com 1 pessoa com princicpal fonte de aquecimento "Natural Gas" usando gastos padroes, sem carro e sem descarte de residuos e iniciando a reciclagem de todas as opcoes', () => {
        cy.get('#ppl-in-household-input').type('1')
        cy.get('#zip-code-input').type('12345')
        cy.get('#get-started').click()
        cy.wait(3000)
        cy.get('.sectionName').contains('Home Energy').should('be.visible')
        cy.scrollTo(500, 0)
        cy.get('#primaryHeatingSource').select('Natural Gas')
        cy.get('#naturalGasTextInput').type('23')
        cy.get('#electricityTextInput').type('44')
        cy.get('#electricityGreenTextInput').type('80')
        cy.get('#fuelTextInput').type('72')
        cy.get('#propaneTextInput').type('37')
        cy.get('#to-transportation').click() 
        cy.get('.sectionName').contains('Transportation').should('be.visible')
        cy.get('#numVehiclesInput').select('0')
        cy.get('#to-waste').click()

        cy.get('.sectionName').contains('Waste').should('be.visible')
        cy.get('#aluminumCheckboxR').click()
        cy.get('#plasticCheckboxR').click()
        cy.get('#glassCheckboxR').click()
        cy.get('#newspaperCheckboxR').click()
        cy.get('#magazinesCheckboxR').click()
        
        cy.get('#to-report').click()
        cy.get('.sectionName').contains('Your Household Carbon Footprint Report').should('be.visible')
    })
})